# Generated by Django 5.1.3 on 2025-02-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_studentresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='exams.exam'),
        ),
    ]
