# Generated by Django 5.1.3 on 2025-03-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
