# Generated by Django 5.1.3 on 2025-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
