# Generated by Django 5.1.3 on 2025-03-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_question_level_question_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='skill',
        ),
    ]
