# Generated by Django 5.1.3 on 2025-03-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_remove_question_level_remove_question_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
