# Generated by Django 5.1.3 on 2025-03-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
