# Generated by Django 5.1.3 on 2025-03-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_remove_question_question_type_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question')], default='MCQ', max_length=20),
        ),
    ]
