# Generated by Django 5.1.3 on 2025-03-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_remove_question_difficulty_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10),
        ),
    ]
