# Generated by Django 5.1.3 on 2025-03-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_remove_question_question_type_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
