# Generated by Django 5.1.3 on 2025-05-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_question_topic_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='easy_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='easy_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='eligibility',
            field=models.CharField(default='Needs Improvement', max_length=20),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='hard_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='hard_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='medium_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='medium_total',
            field=models.IntegerField(default=0),
        ),
    ]
