# Generated by Django 5.1.6 on 2025-05-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_question_topic_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
