# Generated by Django 5.1.3 on 2025-05-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_studentexamattempt_easy_score_and_more'),
        ('exams', '0016_studentexamattempt_feedback'),
    ]

    operations = [
    ]
