# Generated by Django 5.1.3 on 2025-05-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_merge_20250514_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='feedback',
        ),
    ]
