# Generated by Django 5.1.6 on 2025-05-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_remove_studentexamattempt_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='generated_topics',
            field=models.JSONField(default=list),
        ),
    ]
