# Generated by Django 5.1.6 on 2025-05-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_exam_generated_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='generated_topics',
        ),
    ]
