"""
Django settings for my_exam_website project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  #Root project directory path 
SECRET_KEY = 'b)4n$ju!5#5q-4+p(vv6q@e8t0rzw*9yq+h95&m9d(1e!4m)q*'       #Secret key for the project


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/ref/settings/#debug
DEBUG = True 

ALLOWED_HOSTS = ['skilleval.amplelms.com','127.0.0.1'] # List of allowed hosts for the application


# Application definition

INSTALLED_APPS = [      #These are the applications that are installed and available in the project.
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'exams',
]

MIDDLEWARE = [                  #These are layers that process requests/responses globally.
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_exam_website.urls'       #URL configuration for the project

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  #This lets Django look for HTML templates in the main templates/ directory of your project.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_exam_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {       #This is where the database settings are defined.
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', #Using SQLite as the database engine
        'NAME': BASE_DIR / 'db.sqlite3',  #Path to the SQLite database file
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [    #Django built-in validators to ensure secure password creation.
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # Checks if the password is similar to user attributes
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',# Checks if the password is at least a certain length
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',# Checks if the password is not too common
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',# Checks if the password is not entirely numeric
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/ref/settings/#language-code

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/ref/settings/#static-files

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' # Default field type for primary keys

AUTH_USER_MODEL = 'users.User'

# Make sure session expiry is set correctly
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 86400  # 1 day (set a default session expiry)
SESSION_COOKIE_SECURE = False  # Set to True if using HTTPS
SESSION_ENGINE = "django.contrib.sessions.backends.db"  # Store session in DB


CSRF_TRUSTED_ORIGINS = [
    'https://skilleval.amplelms.com',
]
